server {
    listen 80;
    server_name _;
    root /var/www/html/public;

    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_HOST $http_host;
        fastcgi_param HTTP_COOKIE $http_cookie;
        fastcgi_param CONTENT_TYPE $http_content_type;
        fastcgi_param CONTENT_LENGTH $http_content_length;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
